export const productPageType = {
  name: "productPage",
  title: "Dedicated Product Page",
  type: "document",
  fieldsets: [
    { name: "relation", title: "Product Association" },
    { name: "hero", title: "Hero Section Details" },
    { name: "seo", title: "SEO & Search Engine Data", options: { collapsible: true, collapsed: true } },
    { name: "builder", title: "Page Content Sections (Page Builder)" },
  ],
  fields: [
    {
      name: "product",
      title: "Linked Catalog Product",
      type: "reference",
      to: [{ type: "product" }],
      fieldset: "relation",
      validation: (Rule: { required: () => unknown }) => Rule.required(),
    },
    {
      name: "overview",
      title: "Complete Introductory Overview Paragraph",
      type: "text",
      rows: 4,
      fieldset: "hero",
    },
    {
      name: "harvestingProcessing",
      title: "Harvesting & Processing Information",
      type: "text",
      rows: 3,
      fieldset: "hero",
    },
    {
      name: "heroImage",
      title: "Hero Banner Image",
      type: "image",
      fieldset: "hero",
      options: { hotspot: true },
    },
    {
      name: "inquireCtaText",
      title: "Primary Hero Button Text",
      type: "string",
      fieldset: "hero",
      initialValue: "Inquire for Export",
    },
    {
      name: "sourcingCtaText",
      title: "Secondary Hero Button Text",
      type: "string",
      fieldset: "hero",
      initialValue: "Explore Sourcing",
    },
    {
      name: "seoTitle",
      title: "SEO Meta Title",
      type: "string",
      fieldset: "seo",
    },
    {
      name: "seoDescription",
      title: "SEO Meta Description",
      type: "text",
      rows: 3,
      fieldset: "seo",
    },
    {
      name: "pageSections",
      title: "Page Sections (Page Builder)",
      type: "array",
      fieldset: "builder",
      of: [
        { type: "overviewSection" },
        { type: "nutrientsSection" },
        { type: "originSection" },
        { type: "comparisonSection" },
        { type: "sourcingSection" },
        { type: "commitmentsSection" },
        { type: "partnerCtaSection" },
        { type: "faqSection" },
        { type: "customSection" },
      ],
    },
  ],
};
